name: CGL
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  cgl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2, composer-unused
          coverage: none

      # Validation
      - name: Validate composer.json
        run: composer validate --no-check-lock

      # Install dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      # Analyze
      - name: Analyze dependencies
        run: composer cgl analyze:dependencies

      # Linting
      - name: Lint composer.json
        run: composer cgl lint:composer

      - name: Lint .editorconfig
        run: composer cgl lint:editorconfig

      - name: Lint PHP
        run: composer cgl lint:php

      - name: Lint YAML
        run: composer cgl lint:yaml

      # SCA
      - name: SCA PHP
        run: composer cgl sca:php -- --error-format github

      - name: Migration
        run: composer cgl sca:migrate:php --dry-run
