name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  tests:
    name: Tests (PHP ${{ matrix.php-version }}, TYPO3 ${{ matrix.typo3-version }} with ${{ matrix.dependencies }} dependencies)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.2", "8.3", "8.4", "8.5"]
        typo3-version: ["12.4", "13.4"]
        dependencies: ["highest", "lowest"]

    env:
      typo3DatabaseName: typo3
      typo3DatabaseHost: "127.0.0.1"
      typo3DatabaseUsername: root
      typo3DatabasePassword: root

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v${{ matrix.composer-version }}
          coverage: pcov

      # Start MySQL service
      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      # Install dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: >-
            --with=typo3/cms-core:"^${{ matrix.typo3-version }}"
            ${{ matrix.php-version == '8.5' && '--ignore-platform-req=php' || '' }}

      # Run tests
      - name: Run tests
        run: composer test

  tests-coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    env:
      typo3DatabaseName: typo3
      typo3DatabaseHost: "127.0.0.1"
      typo3DatabaseUsername: root
      typo3DatabasePassword: root
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          tools: composer:v2
          coverage: pcov

      # Start MySQL service
      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      # Install dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      # Run tests
      - name: Build coverage directory
        run: mkdir -p .build/coverage
      - name: Run tests with coverage
        run: composer test:coverage

      # Upload artifact
      - name: Fix coverage path
        working-directory: .build/coverage
        run: sed -i 's#/home/runner/work/typo3-typed-extconf/typo3-typed-extconf#${{ github.workspace }}#g' clover.xml
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: .build/coverage/clover.xml
          retention-days: 7

  report-coverage:
    name: Report test coverage
    needs: tests-coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Download artifact
      - name: Download coverage artifact
        id: download
        uses: actions/download-artifact@v4
        with:
          name: coverage

      # qlty
      - name: qlty report
        uses: qltysh/qlty-action/coverage@v1
        if: env.QLTY_COVERAGE_TOKEN
        env:
          QLTY_COVERAGE_TOKEN: ${{ secrets.QLTY_COVERAGE_TOKEN }}
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: ${{ steps.download.outputs.download-path }}/clover.xml

      # Coveralls
      - name: Coveralls report
        uses: coverallsapp/github-action@v2
        with:
          file: ${{ steps.download.outputs.download-path }}/clover.xml
